//! Raw FFI bindings to the SR Research `eyelink_core` C library.
//!
//! These are the ~20 essential functions needed for EyeLink 1000 Plus integration.
//! Bindings are manually declared (not auto-generated by bindgen) to keep the
//! surface area minimal and maintainable.
//!
//! **Build requirement**: The EyeLink Developers Kit must be installed on the
//! build machine. This module is gated behind the `eyelink` Cargo feature.
//!
//! References:
//!   - SR Research EyeLink Programmer's Guide
//!   - core_expt.h from the EyeLink Developers Kit

#![allow(non_camel_case_types, non_snake_case, dead_code)]

use std::os::raw::{c_char, c_short, c_void};

// ============================================================================
// Constants
// ============================================================================

/// Binocular eye indices
pub const LEFT_EYE: usize = 0;
pub const RIGHT_EYE: usize = 1;

/// Connection modes for open_eyelink_connection
pub const CONNECT_NORMAL: c_short = 0;
pub const CONNECT_DUMMY: c_short = -1;

/// Return values
pub const OK_RESULT: c_short = 0;

/// eyelink_is_connected() return values
pub const EYELINK_NOT_CONNECTED: c_short = 0;
pub const EYELINK_CONNECTED: c_short = 1;
pub const EYELINK_BROADCAST: c_short = 2;

/// Sample data flags
pub const SAMPLE_LEFT: u16 = 0x8000;
pub const SAMPLE_RIGHT: u16 = 0x4000;

/// Calibration target beep types (used in CalibrationEvent::PlayBeep)
pub const CAL_TARG_BEEP: i32 = 1;
pub const CAL_GOOD_BEEP: i32 = 0;
pub const CAL_ERR_BEEP: i32 = -1;
pub const DC_TARG_BEEP: i32 = 3;
pub const DC_GOOD_BEEP: i32 = 2;
pub const DC_ERR_BEEP: i32 = -2;

/// Key input constants
pub const JUNK_KEY: c_short = 0;
pub const TERMINATE_KEY: c_short = 27; // ESC
pub const ENTER_KEY: c_short = 13;

// ============================================================================
// Data Types
// ============================================================================

/// Float sample from EyeLink — real-time gaze data.
/// This matches the FSAMPLE struct from edf_data.h / eyelink.h exactly.
///
/// **CRITICAL**: The field order and sizes must match the C ABI precisely.
/// The eyelink_core library writes directly into this struct via pointer cast.
#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
pub struct FSAMPLE {
    /// Timestamp (tracker time, milliseconds)
    pub time: u32,
    /// Pupil x position [left, right]
    pub px: [f32; 2],
    /// Pupil y position [left, right]
    pub py: [f32; 2],
    /// Head-reference x [left, right] (head-mounted only)
    pub hx: [f32; 2],
    /// Head-reference y [left, right] (head-mounted only)
    pub hy: [f32; 2],
    /// Pupil area [left, right]
    pub pa: [f32; 2],
    /// Gaze x position in pixels [left, right] — primary data
    pub gx: [f32; 2],
    /// Gaze y position in pixels [left, right] — primary data
    pub gy: [f32; 2],
    /// Angular resolution: pixels per degree x
    pub rx: f32,
    /// Angular resolution: pixels per degree y
    pub ry: f32,
    // -- Velocity fields (must be present to match C layout) --
    /// Gaze x velocity [left, right]
    pub gxvel: [f32; 2],
    /// Gaze y velocity [left, right]
    pub gyvel: [f32; 2],
    /// Head-reference x velocity [left, right]
    pub hxvel: [f32; 2],
    /// Head-reference y velocity [left, right]
    pub hyvel: [f32; 2],
    /// Resolution x velocity [left, right]
    pub rxvel: [f32; 2],
    /// Resolution y velocity [left, right]
    pub ryvel: [f32; 2],
    /// Filtered gaze x velocity [left, right]
    pub fgxvel: [f32; 2],
    /// Filtered gaze y velocity [left, right]
    pub fgyvel: [f32; 2],
    /// Filtered head-reference x velocity [left, right]
    pub fhxvel: [f32; 2],
    /// Filtered head-reference y velocity [left, right]
    pub fhyvel: [f32; 2],
    /// Filtered resolution x velocity [left, right]
    pub frxvel: [f32; 2],
    /// Filtered resolution y velocity [left, right]
    pub fryvel: [f32; 2],
    // -- End velocity fields --
    /// Head tracker data (raw, not prescaled)
    pub hdata: [c_short; 8],
    /// Flags indicating which fields contain valid data
    pub flags: u16,
    /// Extra input data from tracker
    pub input: u16,
    /// Button state and changes
    pub buttons: u16,
    /// Head tracker data type (0 = none)
    pub htype: c_short,
    /// Process error flags
    pub errors: u16,
}

/// Calibration/graphics hook functions.
/// The EyeLink C API calls back into these function pointers during calibration
/// (triggered by do_tracker_setup). We register our Rust callbacks here to
/// forward calibration events over WebSocket to the frontend.
///
/// **CRITICAL**: This must match the HOOKFCNS typedef in core_expt.h exactly.
/// The C struct has 4 separate beep hooks (not a single play_target_beep), and
/// the return types (void vs INT16) must match precisely.
#[repr(C)]
pub struct HOOKFCNS {
    /// Called to set up the calibration display
    pub setup_cal_display_hook: Option<unsafe extern "C" fn() -> c_short>,
    /// Called when calibration display should close
    pub exit_cal_display_hook: Option<unsafe extern "C" fn()>,
    /// Called when recording should be hidden (abort)
    pub record_abort_hide_hook: Option<unsafe extern "C" fn()>,
    /// Called to set up camera image display
    pub setup_image_display_hook:
        Option<unsafe extern "C" fn(width: c_short, height: c_short) -> c_short>,
    /// Called with camera image title
    pub image_title_hook: Option<unsafe extern "C" fn(threshold: c_short, title: *mut c_char)>,
    /// Called to draw a line of camera image data
    pub draw_image_line_hook: Option<
        unsafe extern "C" fn(
            width: c_short,
            line: *mut c_char,
            totlines: c_short,
            image_line: c_short,
        ),
    >,
    /// Called to set camera image palette
    pub set_image_palette_hook:
        Option<unsafe extern "C" fn(ncolors: c_short, r: *mut u8, g: *mut u8, b: *mut u8)>,
    /// Called when camera image display should close
    pub exit_image_display_hook: Option<unsafe extern "C" fn()>,
    /// Called to clear the calibration display
    pub clear_cal_display_hook: Option<unsafe extern "C" fn()>,
    /// Called to erase the current calibration target
    pub erase_cal_target_hook: Option<unsafe extern "C" fn()>,
    /// Called to draw a calibration target at (x, y)
    pub draw_cal_target_hook: Option<unsafe extern "C" fn(x: c_short, y: c_short)>,
    /// Beep for calibration target presentation
    pub cal_target_beep_hook: Option<unsafe extern "C" fn()>,
    /// Beep when calibration point is done (error=0 means good)
    pub cal_done_beep_hook: Option<unsafe extern "C" fn(error: c_short)>,
    /// Beep when drift-correct point is done
    pub dc_done_beep_hook: Option<unsafe extern "C" fn(error: c_short)>,
    /// Beep for drift-correct target presentation
    pub dc_target_beep_hook: Option<unsafe extern "C" fn()>,
    /// Called to get keyboard input during calibration
    pub get_input_key_hook: Option<unsafe extern "C" fn(event: *mut c_void) -> c_short>,
    /// Called to display alert messages from the tracker
    pub alert_printf_hook: Option<unsafe extern "C" fn(msg: *const c_char)>,
}

// ============================================================================
// FFI Function Declarations
// ============================================================================

extern "C" {
    // -- Connection Management --

    /// Open connection to EyeLink tracker.
    /// mode: 0 = normal, -1 = dummy mode (no tracker needed)
    pub fn open_eyelink_connection(mode: c_short) -> c_short;

    /// Close connection to EyeLink tracker.
    pub fn close_eyelink_connection();

    /// Set the IP address of the EyeLink Host PC.
    /// Must be called before open_eyelink_connection.
    /// Default is "100.1.1.1".
    pub fn set_eyelink_address(addr: *const c_char);

    /// Check connection status.
    /// Returns: 0 = not connected, 1 = connected, 2 = broadcast mode
    pub fn eyelink_is_connected() -> c_short;

    // -- Recording Control --

    /// Start recording with specified data options.
    /// file_samples, file_events: write to EDF file (1=yes, 0=no)
    /// link_samples, link_events: send over link (1=yes, 0=no)
    pub fn start_recording(
        file_samples: c_short,
        file_events: c_short,
        link_samples: c_short,
        link_events: c_short,
    ) -> c_short;

    /// Stop recording.
    pub fn stop_recording();

    // -- Commands and Messages --

    /// Send a command to the tracker (like a remote control).
    /// Uses printf-style formatting. We'll call with pre-formatted strings.
    pub fn eyecmd_printf(cmd: *const c_char, ...) -> c_short;

    /// Send a message to the EDF file (event marker).
    /// This is the primary mechanism for timestamped markers in the EDF recording.
    pub fn eyemsg_printf(msg: *const c_char, ...) -> c_short;

    // -- Real-time Data --

    /// Get the most recent float sample from the link buffer.
    /// Returns: -1 = no new sample, 0 = old sample, 1 = new sample
    pub fn eyelink_newest_float_sample(buf: *mut FSAMPLE) -> c_short;

    /// Get next data item from link buffer.
    pub fn eyelink_get_next_data(buf: *mut c_void) -> c_short;

    // -- Calibration --

    /// Run the full tracker setup (calibration/validation) loop.
    /// This is BLOCKING — it doesn't return until calibration is complete or cancelled.
    /// During execution, it calls the HOOKFCNS callbacks to render targets.
    pub fn do_tracker_setup() -> c_short;

    /// Register graphics hook functions for calibration display.
    pub fn setup_graphic_hook_functions(hooks: *mut HOOKFCNS);

    // -- Tracker Configuration --

    /// Get the tracker software version string.
    pub fn eyelink_get_tracker_version(version_string: *mut c_char) -> c_short;

}

// ============================================================================
// Safe Wrappers
// ============================================================================

/// Safe wrapper to set the EyeLink Host PC address.
///
/// Panics if `addr` contains a NUL byte (should never happen for valid IPs).
pub fn set_address(addr: &str) {
    let c_addr = std::ffi::CString::new(addr).expect("EyeLink address must not contain NUL bytes");
    unsafe {
        set_eyelink_address(c_addr.as_ptr());
    }
}

/// Safe wrapper to open connection.
/// Returns Ok(()) on success, Err with status code on failure.
pub fn connect(mode: c_short) -> Result<(), c_short> {
    let result = unsafe { open_eyelink_connection(mode) };
    if result == OK_RESULT {
        Ok(())
    } else {
        Err(result)
    }
}

/// Safe wrapper to close connection.
pub fn disconnect() {
    unsafe {
        close_eyelink_connection();
    }
}

/// Safe wrapper to check connection status.
pub fn is_connected() -> c_short {
    unsafe { eyelink_is_connected() }
}

/// Safe wrapper to start recording.
pub fn begin_recording(
    file_samples: bool,
    file_events: bool,
    link_samples: bool,
    link_events: bool,
) -> Result<(), c_short> {
    let result = unsafe {
        start_recording(
            file_samples as c_short,
            file_events as c_short,
            link_samples as c_short,
            link_events as c_short,
        )
    };
    if result == OK_RESULT {
        Ok(())
    } else {
        Err(result)
    }
}

/// Safe wrapper to stop recording.
pub fn end_recording() {
    unsafe {
        stop_recording();
    }
}

/// Safe wrapper to send a command to the tracker.
///
/// Uses "%s" format specifier to prevent format string injection —
/// user-provided strings are passed as data arguments, not format strings.
pub fn send_command(cmd: &str) -> Result<(), c_short> {
    let c_cmd = match std::ffi::CString::new(cmd) {
        Ok(s) => s,
        Err(_) => return Err(-1), // NUL byte in string
    };
    let fmt = b"%s\0".as_ptr() as *const c_char;
    let result = unsafe { eyecmd_printf(fmt, c_cmd.as_ptr()) };
    if result == OK_RESULT {
        Ok(())
    } else {
        Err(result)
    }
}

/// Safe wrapper to send a message to the EDF file (marker).
///
/// Uses "%s" format specifier to prevent format string injection —
/// user-provided strings are passed as data arguments, not format strings.
pub fn send_message(msg: &str) -> Result<(), c_short> {
    let c_msg = match std::ffi::CString::new(msg) {
        Ok(s) => s,
        Err(_) => return Err(-1), // NUL byte in string
    };
    let fmt = b"%s\0".as_ptr() as *const c_char;
    let result = unsafe { eyemsg_printf(fmt, c_msg.as_ptr()) };
    if result == OK_RESULT {
        Ok(())
    } else {
        Err(result)
    }
}

/// Safe wrapper to get the newest float sample.
/// Returns Some(sample) if new data is available, None otherwise.
pub fn get_newest_sample() -> Option<FSAMPLE> {
    let mut sample = FSAMPLE::default();
    let result = unsafe { eyelink_newest_float_sample(&mut sample) };
    if result > 0 {
        Some(sample)
    } else {
        None
    }
}

/// Safe wrapper to get tracker version.
pub fn get_tracker_version() -> (c_short, String) {
    let mut version_buf = [0i8; 256];
    let version = unsafe { eyelink_get_tracker_version(version_buf.as_mut_ptr()) };
    let version_str = unsafe {
        std::ffi::CStr::from_ptr(version_buf.as_ptr())
            .to_string_lossy()
            .into_owned()
    };
    (version, version_str)
}

/// Register calibration hook functions.
///
/// # Safety
/// The hooks struct must outlive the calibration session. In practice,
/// we use a static HOOKFCNS instance that lives for the process lifetime.
pub unsafe fn register_hooks(hooks: *mut HOOKFCNS) {
    setup_graphic_hook_functions(hooks);
}
